### PR TITLE
update hash to be a little bit faster at CTFE

### PR DESCRIPTION
**Pull request by UplinkCoder**
pulling the table out of function scope will safe you one copy per evaluation.
It's not much but it is an instant win for almost no code change

### CODE REVIEW

**Comment by TurkeyMan** [comment]
Making it `static` would probably have the same effect without changing its visibility...?

**Comment by UplinkCoder** [comment]
No it does not. 
At least not in my rewrite. :)

**Comment by TurkeyMan** [comment]
So, you're saying CTFE will evaluate static members every execution, rather than once per instantiation? That sounds like low-hanging fruit! Should be easy to cache that... Might speed up lots of code.

**Comment by UplinkCoder** [comment]
It will evaluate them per evaluation!

**Comment by UplinkCoder** [comment]
It's not easy to cache I am afraid.
Because we cannot be sure if it does get modified down the road.

**Comment by TurkeyMan** [comment]
It's immutable...

**Comment by UplinkCoder** [comment]
If it is member of an expression that is appended to. Then we have to copy the literal.
Because the current evaluator has a hard time tracking this we copy literals always.

**Comment by TurkeyMan** [comment]
I'll take your word for it... doesn't sound insurmountable though.

**Comment by UplinkCoder** [comment]
It's of enough of a problem that I started my ctfe-engine from scratch.

**Comment by GooberMan** [comment]
Is that __ctfe symbol fix in a released DMD? I've been sticking on 2.070.2 until LDC gets a 2.071.1-compatible stable release (had compile issues with the alpha release).

**Comment by UplinkCoder** [comment]
you cannot static-if on it. 
And it would not make any sense to reserve capacity at ctfe.

**Comment by UplinkCoder** [comment]
opps deleted the branch by accident.

**Pull request closed without merging**
